

class Dimension:
    CSTR_2 = "cstr_2"
    CSTR_3 = "cstr_3"
    XY_T_POS = "xy_t_pos"
    XY_T_NEG = "xy_t_neg"
    XY_T_POL = "xy_t_pol"
    XY_T_BIN = "xy_t_bin"
    XY_MAX_T_POS = "xy_max_t_pos"
    XY_MAX_T_NEG = "xy_max_t_neg"
    XY_MAX_T_POL = "xy_max_t_pol"
    XY_MAX_T_BIN = "xy_max_t_bin"
    XY_MEAN_T_POS = "xy_mean_t_pos"
    XY_MEAN_T_NEG = "xy_mean_t_neg"
    XY_MEAN_T_POL = "xy_mean_t_pol"
    XY_MEAN_T_BIN = "xy_mean_t_bin"
    XT_MEAN_Y_POS = "xt_mean_y_pos"
    XT_MEAN_Y_NEG = "xt_mean_y_neg"
    XT_MEAN_Y_POL = "xt_mean_y_pol"
    XT_MEAN_Y_BIN = "xt_mean_y_bin"
    TY_MEAN_X_POS = "ty_mean_x_pos"
    TY_MEAN_X_NEG = "ty_mean_x_neg"
    TY_MEAN_X_POL = "ty_mean_x_pol"
    TY_MEAN_X_BIN = "ty_mean_x_bin"
    XY_DENSITY_POS = "xy_density_pos"
    XY_DENSITY_NEG = "xy_density_neg"
    XY_DENSITY_POL = "xy_density_pol"
    XY_DENSITY_BIN = "xy_density_bin"
    XT_DENSITY_POS = "xt_density_pos"
    XT_DENSITY_NEG = "xt_density_neg"
    XT_DENSITY_POL = "xt_density_pol"
    XT_DENSITY_BIN = "xt_density_bin"
    TX_DENSITY_POS = "tx_density_pos"
    TX_DENSITY_NEG = "tx_density_neg"
    TX_DENSITY_POL = "tx_density_pol"
    TX_DENSITY_BIN = "tx_density_bin"
    YT_DENSITY_POS = "yt_density_pos"
    YT_DENSITY_NEG = "yt_density_neg"
    YT_DENSITY_POL = "yt_density_pol"
    YT_DENSITY_BIN = "yt_density_bin"
    TY_DENSITY_POS = "ty_density_pos"
    TY_DENSITY_NEG = "ty_density_neg"
    TY_DENSITY_POL = "ty_density_pol"
    TY_DENSITY_BIN = "ty_density_bin"
    XY_LOG10PDENSITY_POS = "xy_log10pdensity_pos"
    XY_LOG10PDENSITY_NEG = "xy_log10pdensity_neg"
    XY_LOG10PDENSITY_POL = "xy_log10pdensity_pol"
    XY_LOG10PDENSITY_BIN = "xy_log10pdensity_bin"
    XT_LOG10PDENSITY_POS = "xt_log10pdensity_pos"
    XT_LOG10PDENSITY_NEG = "xt_log10pdensity_neg"
    XT_LOG10PDENSITY_POL = "xt_log10pdensity_pol"
    XT_LOG10PDENSITY_BIN = "xt_log10pdensity_bin"
    TX_LOG10PDENSITY_POS = "tx_log10pdensity_pos"
    TX_LOG10PDENSITY_NEG = "tx_log10pdensity_neg"
    TX_LOG10PDENSITY_POL = "tx_log10pdensity_pol"
    TX_LOG10PDENSITY_BIN = "tx_log10pdensity_bin"
    YT_LOG10PDENSITY_POS = "yt_log10pdensity_pos"
    YT_LOG10PDENSITY_NEG = "yt_log10pdensity_neg"
    YT_LOG10PDENSITY_POL = "yt_log10pdensity_pol"
    YT_LOG10PDENSITY_BIN = "yt_log10pdensity_bin"
    TY_LOG10PDENSITY_POS = "ty_log10pdensity_pos"
    TY_LOG10PDENSITY_NEG = "ty_log10pdensity_neg"
    TY_LOG10PDENSITY_POL = "ty_log10pdensity_pol"
    TY_LOG10PDENSITY_BIN = "ty_log10pdensity_bin"
    XY_HIST_POS = "xy_hist_pos"
    XY_HIST_NEG = "xy_hist_neg"
    XY_HIST_POL = "xy_hist_pol"
    XY_HIST_BIN = "xy_hist_bin"
    XT_HIST_POS = "xt_hist_pos"
    XT_HIST_NEG = "xt_hist_neg"
    XT_HIST_POL = "xt_hist_pol"
    XT_HIST_BIN = "xt_hist_bin"
    TX_HIST_POS = "tx_hist_pos"
    TX_HIST_NEG = "tx_hist_neg"
    TX_HIST_POL = "tx_hist_pol"
    TX_HIST_BIN = "tx_hist_bin"
    YT_HIST_POS = "yt_hist_pos"
    YT_HIST_NEG = "yt_hist_neg"
    YT_HIST_POL = "yt_hist_pol"
    YT_HIST_BIN = "yt_hist_bin"
    TY_HIST_POS = "ty_hist_pos"
    TY_HIST_NEG = "ty_hist_neg"
    TY_HIST_POL = "ty_hist_pol"
    TY_HIST_BIN = "ty_hist_bin"
    XY_ZERO = "xy_zero"
    XT_ZERO = "xt_zero"
    TY_ZERO = "ty_zero"


def get_dimension_channel_count(dim: str):
    if dim.startswith("cstr_"): # Special case for CSTR
        return 3
    last_item = dim.split("_")[-1]
    if last_item == "pol":
        return 2
    else: # Includes 'pos', 'neg', 'bin', 'zero'
        return 1



